
ifneq ($(KERNELRELEASE),)

include $(src)/.config

sn9c20x-objs := sn9c20x-usb.o sn9c20x-v4l2.o sn9c20x-sysfs.o
sn9c20x-objs += sn9c20x-dev.o sn9c20x-queue.o
sn9c20x-objs += sn9c20x-bridge.o omnivision.o micron.o hv7131r.o

ifeq ($(CONFIG_SN9C20X_DEBUGFS),y)
#sn9c20x-objs += sn9c20x-debugfs.o
EXTRA_CFLAGS = -DCONFIG_SN9C20X_DEBUGFS
endif

ifeq ($(CONFIG_SN9C20X_EVDEV),y)
EXTRA_CFLAGS += -DCONFIG_SN9C20X_EVDEV
endif

obj-$(CONFIG_SN9C20X) += sn9c20x.o

else

KVER=$(shell uname -r)
KSRC=/lib/modules/$(KVER)/build

all: driver ctags

doc:
	@echo "Generating document with Doxygen..."
	@doxygen Doxyfile

driver:
	$(MAKE) -C $(KSRC) SUBDIRS=$(PWD) modules

ctags:
	@ctags -R

clean:
	$(MAKE) -C $(KSRC) SUBDIRS=$(PWD) clean
	@rm -f Module.symvers Module.markers modules.order tags

cleandoc:
	@echo "Removing documentation generated by Doxygen..."
	@rm -Rf ./doc

insmod:
	@/sbin/insmod sn9c20x.ko

rmmod:
	@/sbin/rmmod sn9c20x

endif
